declare const styles: Readonly<{
  app: string;
  backdrop: string;
  bodyCopy: string;
  card: string;
  cardCopy: string;
  cardEntrance: string;
  cardIndex: string;
  cardMain: string;
  cardRegion: string;
  cardSignal: string;
  customDragArea: string;
  dreamMap: string;
  evidenceGrid: string;
  eyebrow: string;
  footerActions: string;
  footerStack: string;
  handle: string;
  hint: string;
  icon: string;
  inlineImage: string;
  intro: string;
  lede: string;
  loadingState: string;
  locations: string;
  longReport: string;
  mediaHeading: string;
  monogram: string;
  popup: string;
  portal: string;
  presentationControl: string;
  primaryAction: string;
  scene: string;
  secondaryAction: string;
  sheetBody: string;
  sheetContent: string;
  sheetFooter: string;
  sheetHeader: string;
  sheetHeaderMedia: string;
  sheetHeading: string;
  siteHeader: string;
  snapActions: string;
  spinner: string;
  step: string;
  viewport: string;
}>;

export default styles;
